# Generated by Django 6.0.3 on 2026-03-05 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Ejemplo: boston-celtics', unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('color_principal', models.CharField(default='#007A33', help_text='Hexadecimal', max_length=7)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('es_estrella', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='equipos.equipo')),
            ],
        ),
    ]
